version: "3.8"

services:
  # Create 3DCityDB schema
  3dcitydb-db:
    image: 3dcitydb/3dcitydb-pg:14-3.2-4.1.0
    container_name: 3dcitydb-db
    command:
      - "-c"
      - "max_wal_size=4GB"
    environment:
      - POSTGRES_DB=citydb
      - POSTGRES_USER=citydb
      - POSTGRES_PASSWORD=citydb
      - PGUSER=citydb
      - PGDATA=postgres
      - SRID=25832
    ports:
      - "7778:5432"
    networks:
      - citydb-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 3dcitydb-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Load 3DCityDB data
  3dcitydb-impexp:
    image: 3dcitydb/impexp:5.3.0
    container_name: 3dcitydb-impexp
    command:
      - "import"
      - "-H"
      - "host.docker.internal"
      - "-d"
      - "citydb"
      - "-u"
      - "citydb"
      - "-p"
      - "citydb"
      - "/data"
    environment:
      - CITYDB_TYPE=postgresql
      - CITYDB_PORT=7778
      - CITYDB_HOST=localhost
      - CITYDB_NAME=citydb
      - CITYDB_SCHEMA=citydb
      - CITYDB_USERNAME=citydb
      - CITYDB_PASSWORD=citydb
      - SRID=25832
    ports:
      - "7788:5432"
    volumes:
      - ./citygml-data:/data
    depends_on:
      3dcitydb-db:
        condition: service_healthy
    networks:
      - citydb-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Add info on xAL addresses and indexes on GEOGRAPHY PostGIS datatype
  3dcitydb-edit:
    build:
      context: db-edit/
    container_name: 3dcitydb-edit
    depends_on:
      3dcitydb-impexp:
        condition: service_completed_successfully
    networks:
      - citydb-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Start ontop
  ontop:
    image: ontop/ontop:5.1.0
    container_name: ontop
    command: [ "ontop", "materialize", "-f", "turtle", "--output", "/opt/ontop/input/materialized-triples.ttl" ]
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/citygml2.0.owl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/citygml2.0.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/citygml2.0.properties
      ONTOP_LOG_LEVEL: "true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    depends_on:
      3dcitydb-edit:
        condition: service_completed_successfully
    ports:
      - "8082:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jena-fuseki:
    build:
      context: ./jena-fuseki
    container_name: fuseki
    init: true
    environment:
      #- user is "admin"
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx24G
      - TDB=2
    volumes:
      - ./vkg/materialized-triples.ttl:/jena-fuseki/staging/materialized-triples.ttl
    depends_on:
      ontop:
        condition: service_completed_successfully
    ports:
      - "3030:3030"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  d2g2:

networks:
  citydb-net:
    name: citydb-net